### ISSUE TITLE
Restore MZD 

### ISSUE THREAD

**Issue by bremway** [mzdonline/tutorial#2]
Hi @khantaena 
thank you for give me the "CMU bringback" link(https://github.com/mzdonline/tutorial/blob/master/chapter/16_CMU_bringback.md) in the issue i opened in "MZD-AIO-TI" of Trevelopment(https://github.com/Trevelopment/MZD-AIO-TI/issues/18), but still i couldn't fix my CMU. LoL
Since you are a Mazda 2 driver as well(the New Mazda 2 in Taiwan are made in Thailand), i request for assistance here again, i hope i don't bother you but i have no ways better.

My MZD FW: 56.00.513C ADR
i had tried Method 1, Method 2 and Method 3 of Task 1......
For Method 1 and Method 2, i pressed Music + FAV + Pwr/Mute to open diag menu successfully, but then when i long pressed(over 20 seconds), nothing happened, i just couldn't get in the JCI Test Mode, maybe it's closed in 56.00.513.
For Method 3, i didn't recieve any data even ping the CMU via WiFi or USB to Ethernet Device, not to mention the SSH or Telnet.
![imag3813](https://cloud.githubusercontent.com/assets/25223690/22195678/24aabb5e-e184-11e6-9ace-f09b0cf2153e.png)
![screenshot_20170119-205220](https://cloud.githubusercontent.com/assets/25223690/22195714/4acfa27c-e184-11e6-9029-d253b0d8f3e5.png)
![screenshot_20170122-172617](https://cloud.githubusercontent.com/assets/25223690/22195717/4fda1f0e-e184-11e6-946f-eca82ee81b80.png)

What's even worse, i don't have the skill to pull out the MZD computer, so i can't use Method 4. Orz

**Now i have a idea but i'm not sure if it is possible**.......
Since the purpose of all these methods is to get SSH permission to replace this file "/jci/lib/libmc_user.so", to make the USB slots work, then the MZD can be restored via USB that made by MZD-AIO-TI, why we don't just simulate these files to the navi files in a SD card?
that means......
i assume that:
MZD-AIO-TI install/uninstall procedure start form: tweaks.sh
Navigation system start(when we press NAVI button) from: navi.sh
then
1. Make a uninstall all tweaks USB by MZD-AIO-TI
2. Rename the tweaks.sh to navi.sh
3. Copy all the files in the USB to a SD card
4. Put the SD card in the NaviSD slot
5. Press NAVI button
then the uninstall procedure will be executed.

I am not a IT guy so i don't know if it is possible?
Please let me know, thank you!(or you can email to me, too.)

**Comment by khantaena** [comment]
>  i hope i don't bother you but i have no ways better.

No problem.

> I am not a IT guy so i don't know if it is possible?

I'm not sure. I would like to known if has information about your assume.

I suggest you try **Method 1** again. You can send me email khantaena[a t]gmail_com.

**Comment by khantaena** [comment]
close solved
